version: '3'

services:
  traefik:
    image: traefik
    command: --api --docker --docker.exposedbydefault=false
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  consul:
    # Consul will be used to manage service discovery
    image: progrium/consul:latest
    hostname: consul
    command: -server -bootstrap -rejoin
    ports:
      - 8300:8300
      - 8400:8400
      - 8500:8500
      - 8600:53/udp
  rabbit:
    # rabbitmq will be used as message broker to interact with other services
    image: rabbitmq:management
    hostname: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
  listen:
    # listen is the actual listener service
    command: /bin/sh -c "sleep 5; ./listen;"
    image: registry.gitlab.com/gitmate-micro/listen
    build: .
    ports:
      - 80
    environment:
      - MICRO_SERVER_ADDRESS=:80
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul
      - MICRO_BROKER=rabbitmq
      - MICRO_BROKER_ADDRESS=amqp://admin:password@rabbit:5672
    links:
      - consul
      - rabbit
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.backend=listen"
      - "traefik.frontend.rule=Host:listen.traefik"
